pipeline{
    agent any
        stages{
            stage("Stage 1")
            {
                steps{
                    echo "I am in stage 1"
                }
            }
            stage("Stage 2")
            {
                steps{
                    echo "I am in stage 2"
                }
            }
            stage("Stage 3")
            {
                steps{
                    echo "I am in stage 3"
                }
            }
            stage("Stage 4")
            {
                steps{
                    echo "I am in stage 4"
                }
            }
            stage("Stage 5")
            {
                steps{
                    echo "I am in stage 5"
                }
            }
        }
}
