pipeline{
    agent any
    stages {
        stage("Clean Up")
        {
            steps{
                deleteDir()
            }
        }
        stage("Build")
        {
            steps{
                dir("simple-java-maven-app")
                {
                    sh "mvn clean install '-Denforcer.skip'"
                }
            }
        }
        stage("Test")
        {
            steps{
                dir("simple-java-maven-app")
                {
                    sh "mvn test '-Denforcer.skip'"
                }
            }
        }
        stage("End")
        {
            steps{
                echo "Test is ended"
            }
        }
        
    }
}
